import path from 'path';

import webpack, { Configuration, WebpackError } from 'webpack';
import nodeExternals from 'webpack-node-externals';
import { TsconfigPathsPlugin } from 'tsconfig-paths-webpack-plugin';
import CircularDependencyPlugin from 'circular-dependency-plugin';

import { IS_DEV, DIST_DIR, SRC_DIR } from './env';
import fileLoader from './loaders/file';
import cssLoader from './loaders/css';
import jsLoader from './loaders/js';

const Dotenv = require('dotenv-webpack');

const config: Configuration = {
    name: 'server',
    target: 'node',
    node: { __dirname: false },
    entry: path.join(SRC_DIR, 'server'),
    module: {
        rules: [
            fileLoader.server,
            cssLoader.server,
            jsLoader.server,

            {
                test: /\.wav$/i,
                loader: 'null-loader',
            },
        ],
    },
    output: {
        filename: 'server.js',
        libraryTarget: 'commonjs2',
        path: DIST_DIR,
        publicPath: '/static/',
    },
    resolve: {
        modules: ['src', 'node_modules'],
        extensions: ['*', '.js', '.jsx', '.json', '.ts', '.tsx'],
        alias: {
            '@': path.resolve(__dirname, 'src/'),
            ui: path.resolve(__dirname, 'ui/'),
            uicomponents: path.resolve(__dirname, 'ui/components/'),
            components: path.resolve(__dirname, 'src/components/'),
            pages: path.resolve(__dirname, 'src/pages/'),
            services: path.resolve(__dirname, 'src/services/'),
            api: path.resolve(__dirname, 'src/api/'),
            store: path.resolve(__dirname, 'src/store/'),
            utils: path.resolve(__dirname, 'src/utils/'),
        },
        plugins: [new TsconfigPathsPlugin({ configFile: './tsconfig.json' })],
    },

    plugins: [
        new Dotenv(),
        new CircularDependencyPlugin({
            // `onStart` is called before the cycle detection starts
            onStart() {
                console.log('start detecting webpack modules cycles');
            },
            // `onDetected` is called for each module that is cyclical
            onDetected({ paths, compilation }) {
                // `paths` will be an Array of the relative module paths that make up the cycle
                // `module` will be the module record generated by webpack that caused the cycle
                compilation.warnings.push(
                    new Error(paths.join(' -> ')) as WebpackError,
                );
            },
            // `onEnd` is called before the cycle detection ends
            onEnd() {
                console.log('end detecting webpack modules cycles');
            },
        }),
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ],

    devtool: 'source-map',

    performance: {
        hints: IS_DEV ? false : 'warning',
    },

    externals: [nodeExternals({ allowlist: [/\.(?!(?:tsx?|json)$).{1,5}$/i] })],

    optimization: { nodeEnv: false },
};

export default config;
